[MINT-2519] [FE] Notification: Data exchange approach is complete
CMS-Enterprise/mint-app pull request #1453
Opened 2024-10-29 18:57 UTC by garyjzhao

# MINT-2519

## Description

## How to test this change

1.  

## PR Author Checklist

- [ ] I have provided a detailed description of the changes in this PR.
- [ ] I have provided clear instructions on how to test the changes in this PR.
- [ ] I have updated tests or written new tests as appropriate in this PR.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines

- It's best to pull the branch locally and test it, rather than just looking at the code online!
- When approving a PR, provide a reason _why_ you're approving it
  - e.g. "Approving because I tested it locally and all functionality works as expected"
  - e.g. "Approving because the change is simple and matches the Figma design"
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to suggest code comments or documentation updates)
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.

2024-10-29 19:11 UTC, garyjzhao commented on src/components/FormFooter/index.tsx
> +type SubmittionFooterProps = {
This has nothing to do with my code, but making these changes to address type errors

2024-10-29 19:12 UTC, garyjzhao commented on src/features/ModelPlan/Collaborators/AddCollaborator/index.tsx
> +                              : undefined
This has nothing to do with my code, but making these changes to address type errors

2024-10-29 19:47 UTC, patrickseguraoddball requested changes
I'm getting emails, even though I dont have those selected settings.  Not sure if I'm missing a step of the instructions. 

![Screenshot 2024-10-29 at 2 39 11 PM](https://github.com/user-attachments/assets/cecd0c05-9007-4206-aac9-f553e27cf01d)



![Screenshot 2024-10-29 at 2 39 41 PM](https://github.com/user-attachments/assets/d71975b9-81f6-4057-973c-b98a57e91b9c)

Also not getting any notifications in the UI when have the settings selected
![Uploading Screenshot 2024-10-29 at 2.48.30 PM.png…]()

2024-10-29 19:55 UTC, patrickseguraoddball commented
Not seeing this notification come through

![Screenshot 2024-10-29 at 2 55 00 PM](https://github.com/user-attachments/assets/bd1e163b-30d2-4327-bc8f-717f67103b42)

2024-10-30 17:08 UTC, ClayBenson94 approved these changes

2024-10-30 17:09 UTC, merged