[MINT-3199] Custom Category Form Modal
CMS-Enterprise/mint-app pull request #1525
Opened 2024-11-18 19:58 UTC by garyjzhao

# MINT-3199

## Description

## How to test this change

1.  

## PR Author Checklist

- [ ] I have provided a detailed description of the changes in this PR.
- [ ] I have provided clear instructions on how to test the changes in this PR.
- [ ] I have updated tests or written new tests as appropriate in this PR.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines

- It's best to pull the branch locally and test it, rather than just looking at the code online!
- When approving a PR, provide a reason _why_ you're approving it
  - e.g. "Approving because I tested it locally and all functionality works as expected"
  - e.g. "Approving because the change is simple and matches the Figma design"
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to suggest code comments or documentation updates)
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.

2024-11-18 20:02 UTC, garyjzhao commented on src/features/ModelPlan/ModelToOperations/_components/OptionPanel/index.tsx
> +          />
Addressing console warning about key. not directly related to this PR

2024-11-19 16:17 UTC, patrickseguraoddball requested changes
The mobile view is a bit off
![Screenshot 2024-11-19 at 10 11 32 AM](https://github.com/user-attachments/assets/62a957db-95aa-474a-9e99-48c07ff1dded)

If I initially select a primary category, then revert that to unselected, I can still submit the form, and the mutation errors out
![Screenshot 2024-11-19 at 10 13 23 AM](https://github.com/user-attachments/assets/918324be-6233-4b95-a697-15b08713b7f7)

I think we want to handle errors.  There is a mockuo in another Figma, https://www.figma.com/design/BcI7pNwfkmwaDD2EGGTsYC/IT-Lead?node-id=4704-16159&node-type=frame&t=N4Epb7NRxhceenq9-0
Might want to double check with UX

2024-11-19 16:17 UTC, patrickseguraoddball commented on src/i18n/en-US/modelPlan/modelToOperations.ts
> +    cancel: 'Cancel'
For these form questions, we want to handle them to be used in change history.  This includes adding them to `types/translation.ts`.   I don't think we have anything set up yet, but the tables will need to be created and also added to the export util.  I can pair on this if you need!

2024-11-21 20:05 UTC, patrickseguraoddball approved these changes
![Screenshot 2024-11-21 at 2 05 04 PM](https://github.com/user-attachments/assets/36beffee-0377-4d4e-9aa9-fa50495b5104)


There's still this issue with the button being enabled when no category is selected.  It's not really a huge issue since the mutation will fail.  I'll approve anyway and seems like an edge case

2024-11-21 20:28 UTC, merged