[MINT-3220] Add milestone to matrix modal
CMS-Enterprise/mint-app pull request #1558
Opened 2024-12-06 15:06 UTC by patrickseguraoddball

# MINT-3220

## Description

- Added modal/form to add common milestone to MTO
- Adjusted `<Multiselect />` to allow for grouped options and relative styling
- Added unit tests

> [!NOTE]
> This PR also set up the query and form work to support custom solutions.  This work is not yet in place for the BE, so it's commented with a `TODO` tag in the file

## How to test this change

1.  Navigate to MTO matrix milestone library
2. Click Add to matrix on any card
3. Select from a list of the solutions or select none
4. Verify the solutions are not duplicated if they are in the common list
5. Verify Figma/success/error

## PR Author Checklist

- [ ] I have provided a detailed description of the changes in this PR.
- [ ] I have provided clear instructions on how to test the changes in this PR.
- [ ] I have updated tests or written new tests as appropriate in this PR.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines

- It's best to pull the branch locally and test it, rather than just looking at the code online!
- When approving a PR, provide a reason _why_ you're approving it
  - e.g. "Approving because I tested it locally and all functionality works as expected"
  - e.g. "Approving because the change is simple and matches the Figma design"
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to suggest code comments or documentation updates)
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.

2024-12-06 20:57 UTC, garyjzhao requested changes
Milestones are added, but I am not getting any success nor error messages:

https://github.com/user-attachments/assets/ed6301b5-74cb-44ff-84b9-feec788d3101

2024-12-06 21:23 UTC, patrickseguraoddball commented
> Milestones are added, but I am not getting any success nor error messages:
> 

I assumed there was no success message because the button changes to "Added" in green.  I can confirm with Zoe but I think that's where we had landed.  As for the error messages, those should appear in the modal

2024-12-09 14:55 UTC, patrickseguraoddball commented
@garyjzhao Confirmed with Zoe, for now the button is the only intended success state.  May possibly change in the future

2024-12-09 16:40 UTC, ClayBenson94 approved these changes

2024-12-09 16:41 UTC, merged