[MINT-3259] Allow linking milestone on add common solution
CMS-Enterprise/mint-app pull request #1585
Opened 2024-12-26 16:53 UTC by OddTomBrooks

# MINT-3259

## Description

## How to test this change

1. Run scripts/dev test:go and validate unit test success

## PR Author Checklist

- [ ] I have provided a detailed description of the changes in this PR.
- [ ] I have provided clear instructions on how to test the changes in this PR.
- [ ] I have updated tests or written new tests as appropriate in this PR.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines

- It's best to pull the branch locally and test it, rather than just looking at the code online!
- When approving a PR, provide a reason _why_ you're approving it
  - e.g. "Approving because I tested it locally and all functionality works as expected"
  - e.g. "Approving because the change is simple and matches the Figma design"
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to suggest code comments or documentation updates)
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.

2025-01-03 15:09 UTC, StevenWadeOddball requested changes
Thanks Tom. This functions as expected for adding a common solution, but ideally this functionality should be extensible for the update solution modal as well. ( similarly to the recent milestones work).

We should also double check if the work to link solutions when editing a solution is captured anywhere else. I thought it might be included as part of this work, if not here, we should make sure it is captured and uses whatever shared logic is developed here.

2025-01-03 15:27 UTC, StevenWadeOddball commented
Note, [MINT-3142](https://jiraent.cms.gov/browse/MINT-3142) will cover editing a solution. This work should still enable that with shared functionality, but we can make sure to write a task to update the solution update mutation.

2025-01-06 18:34 UTC, StevenWadeOddball commented on pkg/graph/resolvers/mto_solution.go
> +		solution, err := storage.MTOSolutionCreate(tx, logger, mtoSolution)
This is the section of code I'm referring to. You are currently looping through and creating links, and calling a store method for each link.  The solution for linking solutions to a milestone that takes place in `MTOMilestoneUpdateLinkedSolutionsWithTX` is reusable. It also reduces the amount of store calls. 

Currently, this code would not be useable for the update methods. By having a single resolver which can update all the milestones linked to a solution, we could reuse the logic for update. Otherwise, we'd need to refactor this when we implement the functionality for editing a solution.

2025-01-07 21:14 UTC, StevenWadeOddball commented on pkg/sqlqueries/mto_milestone_solution_link.go
> +	LinkMilestonesToSolution string
nit: maybe these should use the same verb as it does for the Milestone centric query? (It might be clearer when we come back to it later that they are doing similar things

2025-01-07 21:14 UTC, StevenWadeOddball commented on pkg/sqlqueries/SQL/mto/milestone_solution_link/link_milestones_to_solution.sql
query looks good!
nit: just around naming the file consistent with the other related query.

2025-01-07 21:18 UTC, StevenWadeOddball approved these changes
🚀  Looks great! Thanks for making that change @OddTomBrooks , I think this will put us in a great place for the edit solution ticket. I put a couple of nits around file / variable naming. Up to you to if you want to change or not, it functions great.

2025-01-07 21:23 UTC, OddTomBrooks commented on pkg/sqlqueries/mto_milestone_solution_link.go
> +	LinkMilestonesToSolution string
This was a conscious decision in that I feel the previous naming convention has some issues. I resisted the urge to rename old methods, perhaps as a 1 point tech lift later.

2025-01-07 21:27 UTC, merged