[MINT-3266] Get all milestones by model plan ID with no solution link
CMS-Enterprise/mint-app pull request #1590
Opened 2024-12-31 21:12 UTC by OddTomBrooks

…do not have a solution link

# MINT-3266

## Description

## How to test this change

1.  Added an endpoint to retrieve all MTO milestones with no linked solution

[!NOTE]
I still need to write a unit test for this, but the rest of the review can be done agnostic while I finish that

## PR Author Checklist

- Use Postman
  - Create a model plan
  - Create an MTO milestone
  - Fetch all MTO milestones with no linked solution, validate that your milestone is retrieved
  - Link your MTO milestone with a custom solution (may require manual winding in the DB)
  - Fetch all MTO milestones with no linked solution, validate that your milestone is not retrieved
  - Unlink your MTO milestone from the custom solution (by deleting the corresponding entry in the custom linking table)
  - Fetch all MTO milestones with no linked solution, validate that your milestone is retrieved
  - Link your MTO milestone with a common solution
  - Fetch all MTO milestones with no linked solution, validate that your milestone is not retrieved
  - Unlink your MTO milestone from the common solution
  - Fetch all MTO milestones with no linked solution, validate that your milestone is retrieved

- [x] I have provided a detailed description of the changes in this PR.
- [x] I have provided clear instructions on how to test the changes in this PR.
- [x] I have updated tests or written new tests as appropriate in this PR.
- [x] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines

- It's best to pull the branch locally and test it, rather than just looking at the code online!
- When approving a PR, provide a reason _why_ you're approving it
  - e.g. "Approving because I tested it locally and all functionality works as expected"
  - e.g. "Approving because the change is simple and matches the Figma design"
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to suggest code comments or documentation updates)
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.

2025-01-03 15:36 UTC, StevenWadeOddball requested changes
Thanks Tom, this is looking pretty good, I think it's almost there. I have some suggestions for the query. Only one piece is a business logic concern ( linking to the common_milestone_solution_link table).

2025-01-03 15:36 UTC, StevenWadeOddball commented on MINT.postman_collection.json
> +										"query": "query GetMTOMilestone {\n    mtoMilestonesWithNoLinkedSolutions(ids: [\"{{mtoMilestoneID}}\"]) {\n    id\n    name\n    key\n    addedFromMilestoneLibrary\n    facilitatedBy\n
This should have this signature, it's invalid curently

```
    mtoMilestonesWithNoLinkedSolutions(modelPlanID:"{{modelPlanID}}") {
```

2025-01-03 15:36 UTC, StevenWadeOddball commented on pkg/graph/schema/types/mto_milestone.graphql
> +  mtoMilestonesWithNoLinkedSolutions(modelPlanID: UUID!): [MTOMilestone!]!
I suspect this should live on the mtoMatrix under model plan, instead of directly on the top level query.

2025-01-03 15:36 UTC, StevenWadeOddball commented on pkg/sqlqueries/SQL/mto/milestone/get_by_model_plan_id_no_linked_solution_LOADER.sql
> +LEFT JOIN mto_common_milestone_solution_link AS cLink
Hmm, I'm not sure that this is a desired behavior. From the AC, I think we are only looking for milestones that aren't directly linked to this specific model plan. `mto_common_milestone_solution_link` is a configuration table to identify solutions that are commonly used for a milestone.

2025-01-03 15:36 UTC, StevenWadeOddball commented on pkg/sqlqueries/SQL/mto/milestone/get_by_model_plan_id_no_linked_solution_LOADER.sql
> +    m.model_plan_id IN (SELECT model_plan_id FROM QIDS)
I think a join would be more appropriate here. We do it most places with a line like this (note you will need to adapt the names to conform since your CTE already has a name. 

`INNER JOIN QUERIED_IDS AS qIDs ON mto_milestone.model_plan_id = qIDs.model_plan_id`

2025-01-03 15:36 UTC, StevenWadeOddball commented on pkg/sqlqueries/SQL/mto/milestone/get_by_model_plan_id_no_linked_solution_LOADER.sql
> +WITH QIDS AS (
Perhaps a verbose name is useful here? we often call this CTE Queried_IDS, then alias it in a join. QIDS doesn't have much intrinsic meaning by itself.

2025-01-15 16:47 UTC, ClayBenson94 commented on pkg/graph/schema/types/mto_milestone.graphql
> +  mtoMilestonesWithNoLinkedSolutions(modelPlanID: UUID!): [MTOMilestone!]!
And, presumably, in that change we could drop the `modelPlanID` param, yeah?

2025-01-15 18:02 UTC, OddTomBrooks commented on pkg/graph/schema/types/mto_milestone.graphql
> +  mtoMilestonesWithNoLinkedSolutions(modelPlanID: UUID!): [MTOMilestone!]!
Yes, this is done locally and will be pushed up shortly. We can source from the mto matrix instead.

2025-01-16 20:53 UTC, StevenWadeOddball requested changes
Thanks @OddTomBrooks, functional testing looks good. Can you please revisit the unit test? We have a a utility function to standardize data loader unit testing. It should be quick change, let me know if you have any questions about how the utility function works `TestMTOMilestoneGetBySolutionIDLoader` is a good example of how to use it

2025-01-16 20:53 UTC, StevenWadeOddball commented on pkg/graph/resolvers/mto_milestone_test.go
> +func (suite *ResolverSuite) TestMTOMilestoneNoLinkedSolutions_MultiplePlans() {
@OddTomBrooks , I'm not sure that this is actually verifying the loader.  If you take a look at `TestMTOMilestoneGetBySolutionIDLoader`, the helper function takes a list of keys, and expected results. It then uses go routines to ensure that test cases hit the data loader at the same time, could you  try to use that helper method here please?

2025-01-16 20:53 UTC, StevenWadeOddball commented on pkg/graph/resolvers/mto_milestone_test.go
> +func (suite *ResolverSuite) TestMTOMilestoneNoLinkedSolutions_SinglePlan() {
This probably doesn't hurt, but I'm not sure you need it if you have multiple test cases in the other loader. Perhaps it's worthwhile to test a case when no results will be returned by SQL at all?

2025-01-16 20:53 UTC, StevenWadeOddball commented on pkg/graph/resolvers/resolver_test.go
> +func (suite *ResolverSuite) getMilestonesWithNoLinkedSolution(
I don't think this function is needed. These functions here are generally are setting up test data. This is abstracting a fetch. I think reworking the unit test to use `VerifyLoaders` would negate the use of this as well.

2025-01-17 18:14 UTC, StevenWadeOddball approved these changes
Thanks @OddTomBrooks

2025-01-17 18:14 UTC, merged